name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mkyoder.jfrog.io/docker-local/hello:latest
    - uses: docker/login-action@v2
    - name: login
      with:
        registry: mkyoder.jfrog.io
        username: ${{ secrets.DOCKER_USERNAME  }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: push docker image
      run: docker push mkyoder.jfrog.io/docker-local/hello:latest
