name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mkyoder.jfrog.io/docker-local/hello:latest
    - name: login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login mkyoder.jfrog.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: push docker image
      run: docker push mkyoder.jfrog.io/docker-local/hello:latest
